import type { Metadata } from "next";
import { Paytone_One } from "next/font/google";
import "../globals.css";
import Navbar from "./_components/Navbar";

const font = Paytone_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Foodiebuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} relative`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
